
package example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HistoryGojekService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:8002/HistoryGojek?wsdl")
public class HistoryGojekService
    extends Service
{

    private final static URL HISTORYGOJEKSERVICE_WSDL_LOCATION;
    private final static WebServiceException HISTORYGOJEKSERVICE_EXCEPTION;
    private final static QName HISTORYGOJEKSERVICE_QNAME = new QName("http://example/", "HistoryGojekService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/HistoryGojek?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HISTORYGOJEKSERVICE_WSDL_LOCATION = url;
        HISTORYGOJEKSERVICE_EXCEPTION = e;
    }

    public HistoryGojekService() {
        super(__getWsdlLocation(), HISTORYGOJEKSERVICE_QNAME);
    }

    public HistoryGojekService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HISTORYGOJEKSERVICE_QNAME, features);
    }

    public HistoryGojekService(URL wsdlLocation) {
        super(wsdlLocation, HISTORYGOJEKSERVICE_QNAME);
    }

    public HistoryGojekService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HISTORYGOJEKSERVICE_QNAME, features);
    }

    public HistoryGojekService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HistoryGojekService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HistoryGojek
     */
    @WebEndpoint(name = "HistoryGojekPort")
    public HistoryGojek getHistoryGojekPort() {
        return super.getPort(new QName("http://example/", "HistoryGojekPort"), HistoryGojek.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HistoryGojek
     */
    @WebEndpoint(name = "HistoryGojekPort")
    public HistoryGojek getHistoryGojekPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "HistoryGojekPort"), HistoryGojek.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HISTORYGOJEKSERVICE_EXCEPTION!= null) {
            throw HISTORYGOJEKSERVICE_EXCEPTION;
        }
        return HISTORYGOJEKSERVICE_WSDL_LOCATION;
    }

}
