
package example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HistoryGojek", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HistoryGojek {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkExpiryTime", targetNamespace = "http://example/", className = "example.CheckExpiryTime")
    @ResponseWrapper(localName = "checkExpiryTimeResponse", targetNamespace = "http://example/", className = "example.CheckExpiryTimeResponse")
    @Action(input = "http://example/HistoryGojek/checkExpiryTimeRequest", output = "http://example/HistoryGojek/checkExpiryTimeResponse")
    public boolean checkExpiryTime(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<example.UserDriverHistory>
     * @throws ClassNotFoundException_Exception
     * @throws InstantiationException_Exception
     * @throws IllegalAccessException_Exception
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverHistory", targetNamespace = "http://example/", className = "example.GetDriverHistory")
    @ResponseWrapper(localName = "getDriverHistoryResponse", targetNamespace = "http://example/", className = "example.GetDriverHistoryResponse")
    @Action(input = "http://example/HistoryGojek/getDriverHistoryRequest", output = "http://example/HistoryGojek/getDriverHistoryResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/HistoryGojek/getDriverHistory/Fault/IllegalAccessException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/HistoryGojek/getDriverHistory/Fault/ParseException"),
        @FaultAction(className = ClassNotFoundException_Exception.class, value = "http://example/HistoryGojek/getDriverHistory/Fault/ClassNotFoundException"),
        @FaultAction(className = InstantiationException_Exception.class, value = "http://example/HistoryGojek/getDriverHistory/Fault/InstantiationException")
    })
    public List<UserDriverHistory> getDriverHistory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws ClassNotFoundException_Exception, IllegalAccessException_Exception, InstantiationException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws IllegalAccessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "hideDriver", targetNamespace = "http://example/", className = "example.HideDriver")
    @ResponseWrapper(localName = "hideDriverResponse", targetNamespace = "http://example/", className = "example.HideDriverResponse")
    @Action(input = "http://example/HistoryGojek/hideDriverRequest", output = "http://example/HistoryGojek/hideDriverResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/HistoryGojek/hideDriver/Fault/IllegalAccessException")
    })
    public void hideDriver(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IllegalAccessException_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws IllegalAccessException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "hidePassanger", targetNamespace = "http://example/", className = "example.HidePassanger")
    @ResponseWrapper(localName = "hidePassangerResponse", targetNamespace = "http://example/", className = "example.HidePassangerResponse")
    @Action(input = "http://example/HistoryGojek/hidePassangerRequest", output = "http://example/HistoryGojek/hidePassangerResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/HistoryGojek/hidePassanger/Fault/IllegalAccessException")
    })
    public void hidePassanger(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IllegalAccessException_Exception
    ;

}
