
package example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Location", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Location {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws IOException_Exception
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "expiryTime", targetNamespace = "http://example/", className = "example.ExpiryTime")
    @ResponseWrapper(localName = "expiryTimeResponse", targetNamespace = "http://example/", className = "example.ExpiryTimeResponse")
    @Action(input = "http://example/Location/expiryTimeRequest", output = "http://example/Location/expiryTimeResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://example/Location/expiryTime/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/Location/expiryTime/Fault/ParseException")
    })
    public int expiryTime(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IllegalAccessException_Exception
     * @throws IOException_Exception
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLocation", targetNamespace = "http://example/", className = "example.AddLocation")
    @ResponseWrapper(localName = "addLocationResponse", targetNamespace = "http://example/", className = "example.AddLocationResponse")
    @Action(input = "http://example/Location/addLocationRequest", output = "http://example/Location/addLocationResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/Location/addLocation/Fault/IllegalAccessException"),
        @FaultAction(className = IOException_Exception.class, value = "http://example/Location/addLocation/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/Location/addLocation/Fault/ParseException")
    })
    public boolean addLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception, IllegalAccessException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws IllegalAccessException_Exception
     * @throws ParseException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteLocation", targetNamespace = "http://example/", className = "example.DeleteLocation")
    @ResponseWrapper(localName = "deleteLocationResponse", targetNamespace = "http://example/", className = "example.DeleteLocationResponse")
    @Action(input = "http://example/Location/deleteLocationRequest", output = "http://example/Location/deleteLocationResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/Location/deleteLocation/Fault/IllegalAccessException"),
        @FaultAction(className = IOException_Exception.class, value = "http://example/Location/deleteLocation/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/Location/deleteLocation/Fault/ParseException")
    })
    public boolean deleteLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception, IllegalAccessException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserLocation", targetNamespace = "http://example/", className = "example.GetUserLocation")
    @ResponseWrapper(localName = "getUserLocationResponse", targetNamespace = "http://example/", className = "example.GetUserLocationResponse")
    @Action(input = "http://example/Location/getUserLocationRequest", output = "http://example/Location/getUserLocationResponse")
    public List<String> getUserLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws ParseException_Exception
     * @throws IOException_Exception
     * @throws IllegalAccessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveLocation", targetNamespace = "http://example/", className = "example.SaveLocation")
    @ResponseWrapper(localName = "saveLocationResponse", targetNamespace = "http://example/", className = "example.SaveLocationResponse")
    @Action(input = "http://example/Location/saveLocationRequest", output = "http://example/Location/saveLocationResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/Location/saveLocation/Fault/IllegalAccessException"),
        @FaultAction(className = IOException_Exception.class, value = "http://example/Location/saveLocation/Fault/IOException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/Location/saveLocation/Fault/ParseException")
    })
    public boolean saveLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException_Exception, IllegalAccessException_Exception, ParseException_Exception
    ;

}
