
package example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderGojekService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:8002/OrderGojek?wsdl")
public class OrderGojekService
    extends Service
{

    private final static URL ORDERGOJEKSERVICE_WSDL_LOCATION;
    private final static WebServiceException ORDERGOJEKSERVICE_EXCEPTION;
    private final static QName ORDERGOJEKSERVICE_QNAME = new QName("http://example/", "OrderGojekService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/OrderGojek?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERGOJEKSERVICE_WSDL_LOCATION = url;
        ORDERGOJEKSERVICE_EXCEPTION = e;
    }

    public OrderGojekService() {
        super(__getWsdlLocation(), ORDERGOJEKSERVICE_QNAME);
    }

    public OrderGojekService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERGOJEKSERVICE_QNAME, features);
    }

    public OrderGojekService(URL wsdlLocation) {
        super(wsdlLocation, ORDERGOJEKSERVICE_QNAME);
    }

    public OrderGojekService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERGOJEKSERVICE_QNAME, features);
    }

    public OrderGojekService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderGojekService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderGojek
     */
    @WebEndpoint(name = "OrderGojekPort")
    public OrderGojek getOrderGojekPort() {
        return super.getPort(new QName("http://example/", "OrderGojekPort"), OrderGojek.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderGojek
     */
    @WebEndpoint(name = "OrderGojekPort")
    public OrderGojek getOrderGojekPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "OrderGojekPort"), OrderGojek.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERGOJEKSERVICE_EXCEPTION!= null) {
            throw ORDERGOJEKSERVICE_EXCEPTION;
        }
        return ORDERGOJEKSERVICE_WSDL_LOCATION;
    }

}
