
package example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderGojek", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderGojek {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<example.Driver>
     * @throws ParseException_Exception
     * @throws IllegalAccessException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPreferredDrivers", targetNamespace = "http://example/", className = "example.GetPreferredDrivers")
    @ResponseWrapper(localName = "getPreferredDriversResponse", targetNamespace = "http://example/", className = "example.GetPreferredDriversResponse")
    @Action(input = "http://example/OrderGojek/getPreferredDriversRequest", output = "http://example/OrderGojek/getPreferredDriversResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/OrderGojek/getPreferredDrivers/Fault/IllegalAccessException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/OrderGojek/getPreferredDrivers/Fault/ParseException")
    })
    public List<Driver> getPreferredDrivers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IllegalAccessException_Exception, ParseException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkExpiryTime", targetNamespace = "http://example/", className = "example.CheckExpiryTime")
    @ResponseWrapper(localName = "checkExpiryTimeResponse", targetNamespace = "http://example/", className = "example.CheckExpiryTimeResponse")
    @Action(input = "http://example/OrderGojek/checkExpiryTimeRequest", output = "http://example/OrderGojek/checkExpiryTimeResponse")
    public boolean checkExpiryTime(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
