
package example;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Profile", targetNamespace = "http://example/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Profile {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<example.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDataUser", targetNamespace = "http://example/", className = "example.GetDataUser")
    @ResponseWrapper(localName = "getDataUserResponse", targetNamespace = "http://example/", className = "example.GetDataUserResponse")
    @Action(input = "http://example/Profile/getDataUserRequest", output = "http://example/Profile/getDataUserResponse")
    public List<User> getDataUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns example.Driver
     * @throws IllegalAccessException_Exception
     * @throws ParseException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDriverByID", targetNamespace = "http://example/", className = "example.GetDriverByID")
    @ResponseWrapper(localName = "getDriverByIDResponse", targetNamespace = "http://example/", className = "example.GetDriverByIDResponse")
    @Action(input = "http://example/Profile/getDriverByIDRequest", output = "http://example/Profile/getDriverByIDResponse", fault = {
        @FaultAction(className = IllegalAccessException_Exception.class, value = "http://example/Profile/getDriverByID/Fault/IllegalAccessException"),
        @FaultAction(className = ParseException_Exception.class, value = "http://example/Profile/getDriverByID/Fault/ParseException")
    })
    public Driver getDriverByID(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0)
        throws IllegalAccessException_Exception, ParseException_Exception
    ;

}
