
package example;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProfileService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:8002/Profile?wsdl")
public class ProfileService
    extends Service
{

    private final static URL PROFILESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROFILESERVICE_EXCEPTION;
    private final static QName PROFILESERVICE_QNAME = new QName("http://example/", "ProfileService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/Profile?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILESERVICE_WSDL_LOCATION = url;
        PROFILESERVICE_EXCEPTION = e;
    }

    public ProfileService() {
        super(__getWsdlLocation(), PROFILESERVICE_QNAME);
    }

    public ProfileService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILESERVICE_QNAME, features);
    }

    public ProfileService(URL wsdlLocation) {
        super(wsdlLocation, PROFILESERVICE_QNAME);
    }

    public ProfileService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILESERVICE_QNAME, features);
    }

    public ProfileService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfileService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Profile
     */
    @WebEndpoint(name = "ProfilePort")
    public Profile getProfilePort() {
        return super.getPort(new QName("http://example/", "ProfilePort"), Profile.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Profile
     */
    @WebEndpoint(name = "ProfilePort")
    public Profile getProfilePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "ProfilePort"), Profile.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILESERVICE_EXCEPTION!= null) {
            throw PROFILESERVICE_EXCEPTION;
        }
        return PROFILESERVICE_WSDL_LOCATION;
    }

}
