
package ojekservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OjekWebApplication", targetNamespace = "http://OjekServices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OjekWebApplication {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "registerDOOServlet", targetNamespace = "http://OjekServices/", className = "ojekservices.RegisterDOOServlet")
    @ResponseWrapper(localName = "registerDOOServletResponse", targetNamespace = "http://OjekServices/", className = "ojekservices.RegisterDOOServletResponse")
    @Action(input = "http://OjekServices/OjekWebApplication/registerDOOServletRequest", output = "http://OjekServices/OjekWebApplication/registerDOOServletResponse", fault = {
        @FaultAction(className = IOException_Exception.class, value = "http://OjekServices/OjekWebApplication/registerDOOServlet/Fault/IOException")
    })
    public void registerDOOServlet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException_Exception
    ;

}
