
package ojekservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OjekWebApplicationService", targetNamespace = "http://OjekServices/", wsdlLocation = "http://localhost:8002/OjekWebApplication?wsdl")
public class OjekWebApplicationService
    extends Service
{

    private final static URL OJEKWEBAPPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException OJEKWEBAPPLICATIONSERVICE_EXCEPTION;
    private final static QName OJEKWEBAPPLICATIONSERVICE_QNAME = new QName("http://OjekServices/", "OjekWebApplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/OjekWebApplication?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OJEKWEBAPPLICATIONSERVICE_WSDL_LOCATION = url;
        OJEKWEBAPPLICATIONSERVICE_EXCEPTION = e;
    }

    public OjekWebApplicationService() {
        super(__getWsdlLocation(), OJEKWEBAPPLICATIONSERVICE_QNAME);
    }

    public OjekWebApplicationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OJEKWEBAPPLICATIONSERVICE_QNAME, features);
    }

    public OjekWebApplicationService(URL wsdlLocation) {
        super(wsdlLocation, OJEKWEBAPPLICATIONSERVICE_QNAME);
    }

    public OjekWebApplicationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OJEKWEBAPPLICATIONSERVICE_QNAME, features);
    }

    public OjekWebApplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OjekWebApplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OjekWebApplication
     */
    @WebEndpoint(name = "OjekWebApplicationPort")
    public OjekWebApplication getOjekWebApplicationPort() {
        return super.getPort(new QName("http://OjekServices/", "OjekWebApplicationPort"), OjekWebApplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OjekWebApplication
     */
    @WebEndpoint(name = "OjekWebApplicationPort")
    public OjekWebApplication getOjekWebApplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://OjekServices/", "OjekWebApplicationPort"), OjekWebApplication.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OJEKWEBAPPLICATIONSERVICE_EXCEPTION!= null) {
            throw OJEKWEBAPPLICATIONSERVICE_EXCEPTION;
        }
        return OJEKWEBAPPLICATIONSERVICE_WSDL_LOCATION;
    }

}
